### ISSUE TITLE
ws-ap3825i: Find out exactly how big the initramfs must get for the suggested bootcmd to fail

### ISSUE THREAD

**Issue by Hurricos** [Hurricos/openwrt#14]
We want to know how to limit the kernel size in the `p1020.mk` build definition Makefile for this target.

To do so:

## Tasks
- [ ] Verify that booting from a compressed kernel fails (past 16M? 32M?)
- [ ] Produce the most forgiving boot instructions possible (largest kernel, though bound *that by ~24MB)
- [ ] Repeatedly pack the initramfs with crap (just `dd` from `/dev/random` into a file in the filesystem under files) until the boot instructions stop working
- [ ] Commit back relevant boundary changes to `p1020.mk`
